# Generated by Django 3.0.1 on 2020-01-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='silicianpizza',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
