# Generated by Django 3.0.1 on 2020-01-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200101_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='type',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Multiple')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='silicianpizza',
            name='type',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Multiple')], default='M', max_length=1),
        ),
    ]
