# Generated by Django 3.0.1 on 2020-01-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200101_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('user', models.CharField(max_length=64)),
            ],
        ),
    ]
