# Generated by Django 3.0.1 on 2020-01-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200102_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
