# Generated by Django 3.0.1 on 2020-01-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
