# Generated by Django 3.0.2 on 2020-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200116_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
